### ISSUE TITLE
Error when running SAS code

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatTag#19]
We have had a report of errors when running SAS code - the log file is showing the following source of the error:

```
[16] ERROR Could not load type 'SAS.LanguageServiceCarriageControl' from assembly 'StatTag.SAS, Version=6.0.3.2, Culture=neutral, PublicKeyToken=null'.
Stack trace:    at SAS.ILanguageService.FlushLogLines(Int32 NumLinesRequested, Array& CarriageControls, Array& LineTypes, Array& LogLines)
   at SAS.SASAutomation.RunCommand(SasServer server, String command)
   at SAS.SASAutomation.RunCommand(String command, Tag tag)
   at SAS.SASAutomation.Initialize(CodeFile file, LogManager logger)
```

**Comment by lrasmus** [comment]
It's possible there is something with our SAS interop DLLs that are causing this problem, although I'm unable to replicate the exact error.  We're going to start with a new build that refreshes the Interop DLLs as an early attempt to fix.

**Comment by lrasmus** [comment]
The error message is misleading to the user - it's showing up as: "We were unable to change the working directory to the location of your code file.   If this problem persists, please contact the StatTag team at StatTag@northwestern.edu."

However we really haven't initialized SAS, so that should be the error shown instead.  We need to attempt to run a noop command just to exercise that whole process.  If that fails, we know it's a SAS initialization issue.

**Comment by lrasmus** [comment]
Not fixed - also getting a different error.  Likely unrelated but tracking here for now:

```
   Unable to communicate with SAS. SAS may not be installed or there might be other configuration issues.
   <connectionAttempts>
     <connectionAttempt>
        <description>Server execution failed
   </description>
        <status>0x80080005</status>
        <saslogin></saslogin>
        <sasmachinednsname>localhost</sasmachinednsname>
        <sasclassid></sasclassid>
        <sasprogid>SAS.Workspace.1.0</sasprogid>
        <threadid>9244</threadid>
     </connectionAttempt>
   </connectionAttempts>
```

**Comment by lrasmus** [comment]
For the object not being found (original issue), given [this thread](https://blogs.sas.com/content/sasdummy/2013/06/09/sas-client-with-microsoft-dot-net/), it sounds like the user must have SAS Integration Technologies installed.  This comes with SAS Enterprise Guide by default, which is likely why I have it but our other user does not.  Will see if [installing SAS Integration Technologies](https://support.sas.com/downloads/browse.htm?fil=&cat=56) addresses the issue.

**Comment by lrasmus** [comment]
Wrote up more about this at:

https://sites.northwestern.edu/stattag/2022/06/30/sas-errors-in-stattag-analysis-and-resolution/
